mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("neuron.urls")),
    path('admin/', admin.site.urls),
]

mysite/neuron/urls.py
from django.urls import path

from . import views

app_name = 'neuron'

urlpatterns = [
	path("", views.index, name="index"),
	path("itemupdate/", views.item_update, name="item_update"),
	path("categoryupdate/", views.category_update, name="category_update"),
]

mysite/neuron/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
# Choice selections

# Model Definitions

class Category(models.Model):
	name = models.CharField(max_length=100, unique = True);

	numItems = models.PositiveIntegerField(default=0,verbose_name = "Number of Items");

	#"toString method"
	def __str__(self):
		return str(f"Category: {self.name}");

class Tag(models.Model):
	name = models.CharField(max_length=100, unique = True);

	#"toString method"
	def __str__(self):
		return str(f"Tag: {self.name}");

class Item(models.Model):
	title = models.CharField(blank=True,max_length=500);

	authors = models.CharField(blank=True,max_length=100);

	date = models.DateField(blank=True,default=date.today().isoformat());

	type = models.CharField(max_length=100, default='Article');

	url = models.URLField(blank=True,max_length=200);

	category = models.ForeignKey(Category, on_delete=models.CASCADE);

	tags = models.ManyToManyField(Tag);

	description = models.TextField(blank=True,max_length=500)

	notes = models.TextField(blank=True,max_length=5000)


	def __str__(self):
		return str(f"Item: {self.title} - {self.authors}");

mysite/neuron/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.template import loader
from .models import Item, Category, Tag
from django.core.serializers.json import DjangoJSONEncoder
from django.forms.models import model_to_dict

import json
from datetime import date

def index(request):
	template = loader.get_template('neuron/index.html')

	item_list = list(Item.objects.all().values());

	for item in item_list:
		#set item date to ISO string format
		item['date'] = item['date'].isoformat();
		#get item category name
		item['category'] = Category.objects.get(id=item['category_id']).name;
		#get list of tags for each item
		item['tags'] = list(Item.objects.get(id=item['id']).tags.all().values_list('name', flat=True));

	category_list = list(Category.objects.all().values());

	tag_list = list(Tag.objects.all().values());

	context = {
		'item_list': item_list,
        'category_list': category_list,
        'tag_list': tag_list,
	}
	return HttpResponse(template.render(context, request))

def category_update(request):
	if request.method == 'POST':
		#if delete item is in the keys of the request
		if 'delete_button' in request.POST.keys():
			#delete the item instead of updating
			cat = Category.objects.get(id = request.POST["category_id"]);
			cat.delete();
		else:
			#find item's corresponding category or create one if new category
			category, created = Category.objects.get_or_create(
			id=request.POST['category_id'],
			defaults = {'name': request.POST['category_name']});

			#if the category was not created, not new, then
			if (not created):
				#find the Tag model instance that shares the category's old name
				#and change that as well.
				try:
					tag = Tag.objects.get(name = category.name);
					tag.name = request.POST['category_name'];
					tag.save();
				except:
					print('Tag with the same name as the old category name does not exist');
				#update the category's name
				category.name = request.POST['category_name'];
				category.save();
	#redirect to index
	return HttpResponseRedirect(reverse("neuron:index"));
def item_update(request):
	if request.method == 'POST':
		#if delete item is in the keys of the request
		if 'delete_button' in request.POST.keys():
			#delete the item instead of updating
			item = Item.objects.get(id = request.POST["item_id"]);
			item.delete();
			item.category.save();
		else:
			#find item's corresponding category or create one if new category
			category, created = Category.objects.get_or_create(
			name=request.POST['item_category']);

			#check through all tags
			#split tag list into array
			tag_list = request.POST['item_tags'].split(',');
			tag_obj_list = [];

			#for each tag in that array get or create
			for tag in tag_list:
				tag_obj, created = Tag.objects.get_or_create(
				name=tag.strip());
				#then add to another array of tag objects
				tag_obj_list.append(tag_obj);

			#get the item with id from form
			#if the item id is not found, it's a new item and is created
			#in that case, the new item is automatically assigned the category
			#in the form.
			item, created = Item.objects.get_or_create(id = request.POST["item_id"],
			defaults = {'category': category});
			item_dict = model_to_dict(item);
			#for each model field of Item, update with the corresponding
			#POST request object
			for field in Item._meta.get_fields():
				#if the field is category/tag set to category/tag object instead
				if field.name == 'category':
					setattr(item,field.name,category);
				elif field.name =='tags':
					for tag_obj in tag_obj_list:
						item.tags.add(tag_obj);
				elif field.name == 'date':
					if request.POST['item_date']!='':
						datetime_conv = date.fromisoformat(request.POST['item_date']);
						setattr(item,field.name,datetime_conv);
				else:
					request_key = str(f"item_{field.name}");
					setattr(item,field.name,request.POST[request_key]);
			item.save();
	#redirect to index
	return HttpResponseRedirect(reverse("neuron:index"));

mysite/neuron/templates/neuron/index.html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/p5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/addons/p5.dom.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/addons/p5.sound.min.js"></script>

    <meta charset="utf-8" />
    {% load static %}
    <link rel="shortcut icon" href="{% static 'neuron/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'neuron/styles.css' %}">
    <script type="text/javascript">
      window.itemTable = {{item_list |safe}};
      window.categoryTable = {{category_list |safe}};
    </script>

  </head>
  <body>
    <div class="top-bar category-section">
      Categories Selected: <span id="category-list"></span>
    </div>
    <div class="top-bar tag-section">
      Tags Selected: <span id="tag-list"></span>
      <form id="tag-display-form" method="post">
        <input id="tag-display-input" type="text" name="tag-name"
        value="" placeholder="Insert tag onto map" autocomplete="off">
      </form>
    </div>
    <div id="canvas-container">

    </div>
    <div id="side-form-overlay" class="rightFormOverlay">
      <div id="side-form-content" class="rightFormContent">
        <form id="item-form" action="{% url 'neuron:item_update' %}" method="post">
      		{% csrf_token %}
          <h4 class="form-section">Title: <input type="text" name="item_title" class="editable long-text" autocomplete="off"></span></h4>
          <p><input type="text" class="editable" name="item_id" value="0" hidden readonly></p>

          <div class="form-section">Authors:
            <input type="text" name="item_authors" class="editable long-text"></div>
          <div class="form-section">Date:
            <input type="text" name="item_date" class="editable" autocomplete="off"></div>
          <div class="form-section">Type:
            <input type="text" name="item_type" class="editable"></div>
          <div class="form-section">URL:
            <input type="text" name="item_url" class="editable long-text" autocomplete="off"></div>
          <div class="form-section">Category:
            <input type="text" name="item_category" class="editable"></div>
          <div class="form-section">Tags:
            <input type="text" name="item_tags" class="editable long-text" autocomplete="off"></div>
          <div class="form-section">Description:
            <textarea name="item_description" rows="3" class="editable"></textarea></div>
          <div class="form-section">Notes:
            <!-- <div id="item-notes" class="editable" style="width: 250px; height: 150px; overflow-y:auto;"></div> -->
            <textarea name="item_notes" rows="10" class="editable"></textarea></div>
          <div class="form-section">
            <button type="submit" form="item-form" name="submit_button">Save</button>
            <button class="cancel-button" form="item-form" name="cancel_button">Cancel</button>
            <br>
            <br>
            <button class="delete-button" type="submit" form="item-form" name="delete_button">Delete</button>
          </div>
        </form>
        <form id="category-form" action="{% url 'neuron:category_update' %}" method="post">
      		{% csrf_token %}
          <h4>Category: <input type="text" name="category_name" class="editable" autocomplete="off"></span></h4>
          <p><input type="text" class="editable" name="category_id" value="0" hidden readonly></p>
          <div class="form-section">
            <button type="submit" form="category-form" name="submit_button"></button>
            <button class="cancel-button" form="category-form" name="cancel_button">Cancel</button>
            <br>
            <br>
            <button class="delete-button" type="submit" form="category-form" name="delete_button">Delete</button>
          </div>
          <div class="form-section" style="overflow:scroll; height:600px;">
            <ul id="item-list">
            </ul>
          </div>
        </form>
      </div>
    </div>
    <script src="{% static 'neuron/sketch.js' %}"></script>
  </body>
</html>